### ISSUE TITLE
Examples of updating Blog Posts programmatically?

### ISSUE THREAD

**Issue by stevenmaguire** [ButterCMS/buttercms-php#9]
@jakelumetta do you have examples of how to update a Blog Post programmatically, using this SDK? If it's within reach, examples of updating Pages would be helpful too!

**Comment by jakelumetta** [comment]
@stevenmaguire the SDK doesn't support Write operations currently so you'll want to do HTTP requests directly to our API. 

- Here's how to update a blog post:  https://buttercms.com/docs/api/#update-blog-post-via-write-api
- Update Page: https://buttercms.com/docs/api/#update-page-via-write-api

**Comment by stevenmaguire** [comment]
Thanks @jakelumetta! 

If I can get something going, are you open to a pull request? I'd also like to add some better support for serializing/deserializing the POPOs in this SDK.

**Comment by jakelumetta** [comment]
Yeah that sounds great! Would love to take a look at a PR.
